In [82]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

In [83]:
path = 'titanic_dataset.csv'
df = pd.read_csv(path)
copy = df.copy()

In [84]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.4 KB

In [85]:
copy.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [86]:
copy.isna().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [87]:
missing = pd.DataFrame(
    {
        "Missing Count": copy.isna().sum().sort_values(ascending=False),
        "Missing Percent":(copy.isna().mean() * 100).round(2).sort_values(ascending=False)
    }
)
missing

             Missing Count  Missing Percent
deck                   688            77.22
age                    177            19.87
embarked                 2             0.22
embark_town              2             0.22
sex                      0             0.00
pclass                   0             0.00
survived                 0             0.00
fare                     0             0.00
parch                    0             0.00
sibsp                    0             0.00
class                    0             0.00
adult_male               0             0.00
who                      0             0.00
alive                    0             0.00
alone                    0             0.00

### Droping 'Deck' column because it has more than 40% of missing value

In [88]:
copy.drop(columns='deck', inplace=True)

In [90]:
copy.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [91]:
copy.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

## Spliting Numerical and Categorical Column

In [92]:
num = ['age', 'sibsp', 'parch', 'fare']
cat = ['pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alone']

In [93]:
# Feature X
# Target Y

x = copy.drop(columns = 'survived')
y= copy.survived

In [94]:
x.head(2)

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False

In [95]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [96]:
X_train, X_test, y_train, y_test= train_test_split(x,
                                                   y,
                                                   random_state= 42,
                                                   stratify=y)

In [97]:
print("Data split Ratio")
ratio = pd.DataFrame(
    {
        'y_count': y.value_counts(),
        'y_percent': y.value_counts(normalize=True),
        'y_test_count': y_test.value_counts(),
        'y_test_percent': y_test.value_counts(normalize=True)
    }
)
ratio

Data split Ratio

          y_count  y_percent  y_test_count  y_test_percent
survived
0             549   0.616162           137         0.61435
1             342   0.383838            86         0.38565

In [98]:
X_train

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
486,1,female,35.00,1,0,90.0000,S,First,woman,False,Southampton,yes,False
238,2,male,19.00,0,0,10.5000,S,Second,man,True,Southampton,no,True
722,2,male,34.00,0,0,13.0000,S,Second,man,True,Southampton,no,True
184,3,female,4.00,0,2,22.0250,S,Third,child,False,Southampton,yes,False
56,2,female,21.00,0,0,10.5000,S,Second,woman,False,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,2,male,NaN,0,0,13.8625,C,Second,man,True,Cherbourg,yes,True
469,3,female,0.75,2,1,19.2583,C,Third,child,False,Cherbourg,yes,False
736,3,female,48.00,1,3,34.3750,S,Third,woman,False,Southampton,no,False
462,1,male,47.00,0,0,38.5000,S,First,man,True,Southampton,no,True
821,3,male,27.00,0,0,8.6625,S,Third,man,True,Southampton,yes,True

## Handling missing Numerical values

In [101]:
a = [X_train, X_test, y_train, y_test]

num = ['age', 'sibsp', 'parch', 'fare']
cat = ['pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alone']
X_train.isna().sum()

pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

### Filling missing value using the Simple Imputer

In [103]:
from sklearn.impute import SimpleImputer

SI1= SimpleImputer(strategy="median")
SI2= SimpleImputer(strategy="most_frequent")

X_train['age']= SI1.fit_transform(X_train[['age']])
X_test['age']= SI1.transform(X_test[['age']])

X_train[cat]= SI2.fit_transform(X_train[cat])
X_test[cat]= SI2.transform(X_test[cat])

In [104]:
X_train.isna().sum()

pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [105]:
y_train.isna().sum()

np.int64(0)