In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('titanic_dataset.csv')
copy = df.copy()
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
num = ['age', 'sibsp', 'parch', 'fare']
cat = ['pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'emark_town', 'alone']

In [6]:
missing = pd.DataFrame(
    {
        "Missing Count": df.isna().sum().sort_values(ascending=False),
        "Missing Percent":(df.isna().mean() * 100).round(2).sort_values(ascending=False)
    }
)
missing

             Missing Count  Missing Percent
deck                   688            77.22
age                    177            19.87
embarked                 2             0.22
embark_town              2             0.22
sex                      0             0.00
pclass                   0             0.00
survived                 0             0.00
fare                     0             0.00
parch                    0             0.00
sibsp                    0             0.00
class                    0             0.00
adult_male               0             0.00
who                      0             0.00
alive                    0             0.00
alone                    0             0.00

In [7]:
df.deck.unique()

<StringArray>
[nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Length: 8, dtype: str

In [8]:
# Features X
# Target y

target = 'survived'

In [9]:
X = df.drop(columns='survived')
y = df[target]

In [10]:
print("Data split Ratio")
ratio = pd.DataFrame(
    {
        'y_count': y.value_counts(),
        'y_percent': y.value_counts(normalize=True).round(2)
    }
)
ratio

Data split Ratio

          y_count  y_percent
survived
0             549       0.62
1             342       0.38

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
print("Train Test Shape")
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print()
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

Train Test Shape
X_train:  (712, 14)
y_train:  (712,)

X_test:  (179, 14)
y_test:  (179,)

In [13]:
X_test.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
565,3,male,24.0,2,0,24.1500,S,Third,man,True,NaN,Southampton,no,False
160,3,male,44.0,0,1,16.1000,S,Third,man,True,NaN,Southampton,no,False
553,3,male,22.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,yes,True
860,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,no,False
241,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,yes,False

In [14]:
import numpy as np

In [15]:
np.random.seed(seed=1)
np.random.rand()

0.417022004702574

In [16]:
print("Data split Ratio")
ratio = pd.DataFrame(
    {
        'y_count': y.value_counts(),
        'y_percent': y.value_counts(normalize=True),
        'y_test_count': y_test.value_counts(),
        'y_test_percent': y_test.value_counts(normalize=True)
    }
)
ratio

Data split Ratio

          y_count  y_percent  y_test_count  y_test_percent
survived
0             549   0.616162           110        0.614525
1             342   0.383838            69        0.385475

# Handle missing values Numerical

In [17]:
a = [X_train, X_test, y_train, y_test]
num

['age', 'sibsp', 'parch', 'fare']

In [18]:
for i in num:
    m = X_train[i].median()
    X_train[i].fillna(m, inplace=True)
    X_test[i].fillna(m, inplace=True)

C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_train[i].fillna(m, inplace=True)
C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_test[i].fillna(m, inplace=True)
C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_train[i].fillna(m, inplace=True)
C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_test[i].fillna(m, inplace=True)
C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_train[i].fillna(m, inplace=True)
C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_test[i].fillna(m, inplace=True)
C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_train[i].fillna(m, inplace=True)
C:\Users\yoges\AppData\Local\Temp\ipykernel_4252\3415396314.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X_test[i].fillna(m, inplace=True)

In [19]:
missing = pd.DataFrame(
    {
        "Missing Count": X_train.isna().sum().sort_values(ascending=False),
        "Missing Percent":(X_test.isna().mean() * 100).round(2).sort_values(ascending=False)
    }
)
missing

             Missing Count  Missing Percent
adult_male               0             0.00
age                    137            22.35
alive                    0             0.00
alone                    0             0.00
class                    0             0.00
deck                   553            75.42
embark_town              2             0.00
embarked                 2             0.00
fare                     0             0.00
parch                    0             0.00
pclass                   0             0.00
sex                      0             0.00
sibsp                    0             0.00
who                      0             0.00

In [ ]:
num = ['age', 'sibsp', 'parch', 'fare']
cat = ['pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alone']

# Numerical

In [44]:
misval=[]
for i in copy.columns:
    per= copy[i].isna().mean()*100
    if(per > 40.0):
        misval.append(i)

print(misval)

[]

In [45]:
copy.drop(columns = misval,inplace=True)

In [46]:
copy.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [47]:
print(df['age'].median())
print(df['age'].mean())
print(df['age'].mode()[0])

28.0
29.69911764705882
24.0

In [48]:
print(copy.age.isna().sum())

age_median = copy.age.median()

copy.age = copy.age.fillna(age_median).isna().sum()

print(copy.age.isna().sum())

177
0

# Categorical

In [56]:
# Categorical
print(cat)
for i in cat:
    if(i == 'deck'):
        continue
    cat_mode = copy[i].mode()[0]
    copy[i]=copy[i].fillna(cat_mode)
print(copy.columns)

['pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alone']
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [58]:
copy.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64